apiVersion: apps/v1
kind: Deployment
metadata:
  name: sash-kafka
  labels:
    app: sash-kafka
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sash-kafka
      version: v1
  template:
    metadata:
      labels:
        app: sash-kafka
        version: v1
    spec:
      containers:
        - name: sash-kafka
          image: "gcr.io/moses-327312/sash-kafka:v1"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: QUARKUS_HTTP_PORT
              value: "8080"
