apiVersion: v1
kind: Service
metadata:
  name: sash-http-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: sash-http
    version: v1